<?php
require_once './../util/initialize.php';
?>
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <title></title>

    <style>
        td {
            font-size: 12px;
        }

        th {
            font-size: 13px;
        }
    </style>
</head>

<body>

    <table style="width:700px;">
        <tr>

            <td colspan="2" style="text-align:center;">
                <p style="font-size:15px;text-transform: uppercase;"><b style="font-size:20px;"><?php echo ProjectConfig::$project_name; ?></b> <br /> NO: 332/29, LESSLISS LAND, RATHNAPURA ROAD, MUNAGAMA, HOARANA. <br />
                    TEL: <?php echo ProjectConfig::$tel_html; ?> || FAX: 011 588 3813 || HOTLINE: 0777 191 784 / 0703 963 615</p>

                <p style="font-weight:900;">
                    <?php echo Customer::find_by_id($_GET["cus"])->name; ?> Write-Off REPORT ( <?php echo date('d-m-Y') . " @ " . date('h:s:m'); ?> ) GENERATED BY: <?php echo $_SESSION["user"]["name"]; ?> </p>
                </p>
            </td>

        </tr>



    </table>

    <div>

        <!-- table starts -->
        <table id="datatable-responsive" class="" cellspacing="0" width="700px">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Customer Name</th>
                    <th>Invoice</th>
                    <th style='text-align:right;'>Amount</th>
                    <th style='text-align:right;'>Writeoff Date</th>

                </tr>
            </thead>
            <tbody>
                <?php
                foreach (WriteOff::find_by_customer_id($_GET["cus"]) as $write_off_data) {
                ?>
                    <tr>
                        <td class="col-md-1"><?php echo "RO" . $write_off_data->id  ?></td>
                        <td class="col-md-1"><?php echo $write_off_data->invoice_id()->customer_id()->name  ?></td>
                        <td class="col-md-1"><?php echo $write_off_data->invoice_id()->code ?></td>
                        <td class="col-md-1" style='text-align:right;'><?php echo number_format($write_off_data->amount, 2); ?></td>
                        <td class="col-md-1" style='text-align:right;'><?php echo $write_off_data->write_off_date ?></td>
                    </tr>
                <?php
                }
                ?>
            </tbody>
        </table>

        <!-- table ends -->

    </div>



</body>
<script type="text/javascript">
    window.print();
</script>

</html>