<?php
require_once './../util/initialize.php';
include 'common/upper_content.php';
?>

<!--page content--> 

<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Stock Details</h3>
            </div>

            <div class="title_right">
                <button type="button" id="btn_print" class="btn btn-default" style="float: right;"><i class="glyphicon glyphicon-print"></i>  Print</button>
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
            <div class="row" id="divInvoice">

                <div class="col-md-12 col-sm-12 col-xs-12 table-responsive" id="print_div">
                    <div class="x_panel">
                        <div class="x_title" style="background-color: #424242;color:white;border-radius: 5px 5px 0px 0px;"><h3><center>Main Stock Report</center></h3></div>
                        <div class="x_content">
                            <div class="table-responsive">

                                <table id="sata_table" class="table table-striped " cellspacing="0" >

                                    <tbody id="table_body">
                                        <?php
                                        foreach (Product::find_all() as $product) {
                                            $inventories = Inventory::find_all_calculated_qty_by_product_id($product->id);
                                            if (count($inventories) > 0) {
                                                ?>
                                                <tr style="background-color: #989898;" >
                                                    <td colspan="1" style="color: #fff;"><b><?= $product->name ?></b></td>
                                                    <!--<td colspan="3"><b>&nbsp;</b></td>-->
                                                    <td style="color: #000; text-align: center;"><b>Batch No</b></td>
                                                    <td style="color: #000; text-align: center;"><b>Qty</b></td>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                <?php
                                                $line_total = 0;
                                                foreach ($inventories as $inventory) {
                                                    $batch = $inventory->batch_id();
                                                    $line_total += $inventory->qty;
                                                    ?>

                                                    <tr style="background-color: lightgray;color: #000; text-align: center;" >
                                                        <td>&nbsp;</td>
                                                        <td><?php echo $batch->code; ?></td>
                                                        <td><?php echo $inventory->qty; ?></td>
                                                        <td>&nbsp;</td>
                                                    </tr>
                                                    <?php
                                                }
                                                ?>
                                                <tr style="background-color: lightgray;color: #000; " >
                                                    <td>Total:</td>
                                                    <td>&nbsp;</td>
                                                    <td style="background-color: #fff;color: #000; text-align: center;"><b><?= $line_total ?></b></td>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                <?php
                                            }
                                        }
                                        ?>
                                    </tbody>
                                    <tfoot style="margin-top: 10px;">
<!--                                        <tr><td colspan="9">&nbsp;</td></tr>-->
                                        <tr style="background-color: #424242;color: white;">
                                            <td colspan="9" style="text-align: center;">Report Generated by <?= $_SESSION['user']['name'] . " on " . date("Y/m/d") . " at " . date("h:i:sa"); ?></td>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /page content -->

<?php include 'common/bottom_content.php'; ?>

<script>
    //print_div

    $('#btn_print').click(function () {
        PrintDiv();
    });

    function PrintDiv() {
        var divToPrint = document.getElementById('print_div');
        var popupWin = window.open('', '_blank', 'width=800,height=500');
        popupWin.document.open();
        popupWin.document.write('<html><head><link href="../vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet"></head><body onload="window.print()">' + divToPrint.innerHTML + '</html>');
        popupWin.document.close();
    }
</script>
