<?php
require_once './../util/initialize.php';
?>
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <title></title>

  <style>
  td{
    font-size: 12px;
  }
  th{
    font-size: 13px;
  }
  </style>
</head>
<body>

  <table style="width:700px;">
    <tr>

      <td colspan="2" style="text-align:center;">
        <p style="font-size:15px;text-transform: uppercase;"><b style="font-size:20px;"><?php echo ProjectConfig::$project_name; ?></b> <br/> NO: 332/29, LESSLISS LAND, RATHNAPURA ROAD, MUNAGAMA, HOARANA. <br/>
          TEL: <?php echo ProjectConfig::$tel_html; ?> || FAX: 011 588 3813 || HOTLINE: 0777 191 784 / 0703 963 615</p>

          <p style="font-weight:900;">
            
          OUTSTANDING REPORT ( <?php echo date('d-m-Y')." @ ".date('h:s:m'); ?> ) GENERATED BY: <?php echo $_SESSION["user"]["name"]; ?>  </p>
        </td>

      </tr>



    </table>

    <div>

      <!-- table starts -->

      <table id="datatable-responsive" class="" cellspacing="0" width="700px">
        <thead>
          <tr>
            <!--<th>ID</th>-->
            <th style="text-align: left;">Invoice Number</th>
            <th style="text-align:right;">Date</th>
            <th style="text-align:right;">Net Invoice Amount</th>
            <th style="text-align:right;">Paid Amount</th>
            <th style="text-align:right;">Balance</th>
          </tr>
        </thead>
        <tbody>
          <?php
          $total = 0;

          $customer = Customer::find_by_id($_GET["cus_id"]);

          $tone = 0;
          $ttwo =0;
          $tthree = 0;
          $tfour = 0;
          $tfive = 0;
          $tsix = 0;
          $ta = 0;

          $full_total = 0;

          $invoices = Invoice::customer_id_pending($customer->id);
          $inv_count = count($invoices);

          $outperiod = $customer->period;

          if ($inv_count != 0) {
            ?>
            <tr>
              <td colspan="8" style="text-align: left; padding-top: 10px;">
                <?php
                $balance = 0;
                $balance_str = "";

                echo $customer->name . " ( " . $customer->address . " ) " . $customer->phone;
                ?>
              </td>
            </tr>
            <tr>
              <td colspan="9"><hr style="margin: 0px 0px 5px;"/></td>
            </tr>

            <?php
            $one = 0;
            $two = 0;
            $three = 0;
            $four = 0;
            $five = 0;
            $six = 0;
            $line_total = 0;
            $total_balance = 0;
            foreach ($invoices as $invoice) {
              ?>
              <tr>
                <td style="text-align:left;border-bottom:1px solid;padding-top:3px;"><?php echo $invoice->code; ?></td>
                <td style="text-align: right;border-bottom:1px solid;padding-top:3px;"><?php echo $invoice->date_time; ?></td>
                <td style="text-align: right;border-bottom:1px solid;padding-top:3px;"><?php echo number_format($invoice->net_amount,2); ?></td>
                <td style="text-align: right;border-bottom:1px solid;padding-top:3px;"><?php echo number_format($invoice->net_amount - $invoice->balance,2); ?></td>
                <td style="text-align: right;border-bottom:1px solid;padding-top:3px;"><?php echo number_format($invoice->balance,2); ?></td>
              </tr>
              <?php
              $total_balance = $total_balance + $invoice->balance;

            }

            ?>
            <tr style="font-weight:800;">
              <td colspan="4" style="text-align:right;">CUSTOMER TOTAL BALANCE</td>
              <td style="text-align: right;"><?php echo number_format($total_balance,2); ?></td>
            </tr>
            <?php
            $full_total = $full_total + $total_balance;
          }

          ?>

          <tr style="font-weight:800;font-size:17px;">
            <td colspan="4" style="text-align:right;padding-top:20px;">TOTAL BALANCE</td>
            <td style="text-align: right;padding-top:20px;"><?php echo number_format($full_total,2); ?></td>
          </tr>

        </tbody>
        <tfoot>
          <tr>
            <td colspan='5' style="font-size:15px;">
          <p>METHODS OF PAYMENTS: CASH/CHEQUE</p>
          <ul>
            <li>You should pay in cash at Sampath Bank Account Number: 0057 1000 5437</li>
            <li>Cheques should be drawn in favour of South Asian Automobiles (Pvt) Ltd Only.</li>
            <li>Cheques issued by third Parties or Cash Cheques will not be accepted.</li>
            <li>Cheques are credited to your account subject to realization.</li>
            <li>Not responsible for the cheques or cash deposits slips without obtaining a valid acknowledgement reciept from our company representative.</li>
            <li>Cheques returns will be charged Rs.500.00</li>
            <li>According to Debit Recovery law of Sri Lanka,  Dishonoring of Cheque is an offensive punishable after a summery trial, Section 25(I) of debt recovery special problem Act No.02 of 1990 Provide:</li>

          </ul>
        </td>
        </tr>
        </tfoot>
      </table>

      <!-- table ends -->

    </div>
    <!-- <div class="col-sm-12" style='font-size:15px;'>
      <p>METHODS OF PAYMENTS: CASH/CHEQUE</p>
      <ul>
        <li>You should pay in cash at Sampath Bank Account Number: 0057 1000 5437</li>
        <li>Cheques should be drawn in favour of South Asian Automobiles (Pvt) Ltd Only.</li>
        <li>Cheques issued by third Parties or Cash Cheques will not be accepted.</li>
        <li>Cheques are credited to your account subject to realization.</li>
        <li>Not responsible for the cheques or cash deposits slips without obtaining a valid acknowledgement reciept from our company representative.</li>
        <li>Cheques returns will be charged Rs.500.00</li>
        <li>According to Debit Recovery law of Sri Lanka,  Dishonoring of Cheque is an offensive punishable after a summery trial, Section 25(I) of debt recovery special problem Act No.02 of 1990 Provide:</li>

      </ul>
    </div> -->

    <div class="col-sm-12" style='font-size:12px;text-align:center;margin-top:30px;'>
      This is a computer generated statement. If need clarifications, Please contact 011 588 3810 or 0777 191784
    </div>




  </body>
  <script type="text/javascript">

  window.print();

  </script>
  </html>
