<?php
require_once './../util/initialize.php';
include 'common/upper_content.php';
?>

<!--page content-->

<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Re-Order Details</h3>
      </div>

      <div class="title_right">
        <button type="button" id="btn_print" class="btn btn-default" style="float: right;"><i class="glyphicon glyphicon-print"></i>  Print</button>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">

      <!-- FORM START -->
      <div class="x_panel">
        <form class="form-horizontal" method="post" action="re_order_report.php" >

          <div class="form-group">
            <label class="control-label col-sm-2" >Brand:</label>
            <div class="col-sm-10">
              <select name="brand" class="form-control">
                <?php
                foreach (Product::find_all_by_distinct_brand() as $data) {
                  echo "<option>".$data->brand."</option>";
                }
                ?>
              </select>
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-primary">View</button>
            </div>
          </div>

        </form>
      </div>
      <!-- FORM ENDS -->

      <div class="row" id="divInvoice">

        <div class="col-md-12 col-sm-12 col-xs-12 table-responsive" id="print_div">
          <div class="x_panel">
            <div class="x_title" style="background-color: #424242;color:white;border-radius: 5px 5px 0px 0px;"><h3><center>Re-Order Report (<?php if(isset($_POST['brand'])){ echo $_POST['brand']; } ?>) </center></h3>
              <p><center>Generated By: <?php echo $_SESSION["user"]["name"]; ?></center></p>
            </div>
            <div class="x_content">
              <div class="table-responsive">

                <table id="sata_table" class="table table-striped " cellspacing="0" width="100%">
                  <thead>


                  </thead>
                  <tbody id="table_body">
                    <?php
                    if(isset($_POST['brand'])){
                    foreach (Category::find_all() as $category) {
                      $inventory_details = Inventory::find_all_by_category_id($category->id);
                      $category_name     = $category->name;
                      $sub_total = 0;?>
                      <tr style="background-color: gray;color:black;"><td colspan="10" ><b><?=$category_name?></b></td></tr>
                      <tr>
                        <th>&nbsp;</th>
                        <th>&nbsp;</th>
                        <th>Batch Code</th>
                        <th>Product</th>
                        <th style="text-align:center;">ROQ</th>
                        <th style="text-align:center;">Max Qty</th>
                        <th style="text-align:center;">Min Qty</th>
                        <th style="text-align:center;">Stock Qty</th>
                        <th style="text-align:right;">Unit Price <br/> USD</th>
                        <th style="text-align:right;">Line Total</th>

                      </tr>
                      <?php

                      foreach ($inventory_details as $inventory_detail) {
                        $batch_details   = Batch::find_by_id($inventory_detail['batch_id']);
                        $product_details = Product::find_by_id($inventory_detail['product_id']);
                        $product_name    = Product::find_by_id($inventory_detail['product_id'])->name;


                        if($product_details->brand == $_POST['brand']){

                          $line_total      = ($inventory_detail['qty']) * ($batch_details->dollar_rate);
                          $sub_total      = $sub_total + $line_total;

                        ?>

                        <tr>
                          <td>&nbsp;</td>
                          <td>&nbsp;</td>
                          <td><?=$batch_details->code?></td>
                          <td><?=$product_name?></td>
                          <td style="text-align:center;"><?=$product_details->roq?></td>
                          <td style="text-align:center;"><?=$product_details->max_qty?></td>
                          <td style="text-align:center;"><?=$product_details->min_qty?></td>
                          <td style="text-align:center;"><?=$inventory_detail['qty']?></td>
                          <td style="text-align:right;"><?= $batch_details->dollar_rate ?></td>
                          <td style="text-align:right;"><?= $line_total ?></td>

                        </tr>

                        <?php
                      }
                      }
                      ?>
                      <tr style="background-color: lightgray;color: black;" >
                        <td colspan="5"><b>&nbsp;</b></td>
                        <td colspan="3"><b>&nbsp;</b></td>
                        <td colspan="1" style="text-align:right;"><b>Total Value</b></td>
                        <td colspan="1" style="text-align:right;"><b><?=$sub_total?></b></td>
                      </tr>
                      <?php
                    }
                  }
                    ?>
                  </tbody>
                  <tfoot style="margin-top: 10px;">
                    <!--                                        <tr><td colspan="9">&nbsp;</td></tr>-->

                    <tr style="background-color: #424242;color: white;">
                      <td colspan="10" style="text-align: center;">Report Generated by <?=$_SESSION['user']['name']." on ".date("Y/m/d")." at ".date("h:i:sa");?></td>
                    </tr>
                  </tfoot>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /page content -->

<?php include 'common/bottom_content.php'; ?>

<script>

//print_div

$('#btn_print').click(function (){
  PrintDiv();
});

function PrintDiv() {
  var divToPrint = document.getElementById('print_div');
  var popupWin = window.open('', '_blank', 'width=800,height=500');
  popupWin.document.open();
  popupWin.document.write('<html><head><link href="../vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet"></head><body onload="window.print()">' + divToPrint.innerHTML + '</html>');
  popupWin.document.close();
}
</script>
